

- name: instalar apache no Debian
  apt:
   name: apache2
   state: present
  when: ansible_os_family == "Debian"

- name: instalar apache no CentOS
  yum:
   name: httpd
   state: present
  when: ansible_os_family == "RedHat"

