

- name: instalando pacotes necessarios ao Docker
  package:
   name: "{{ item }}"
   update_cache: yes
   state: present
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
