

- name: importar certificado GPG para validar repositorio Docker
  apt_key:
   id: 0EBFCD88
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present

- name: download e instalacao repositorio Ubuntu - Debian para Docker
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
   state: present
